# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/93e10387-75ba-4f7a-a717-019420f7ac62";
      fsType = "btrfs";
      options = [ "subvol=@nixroot" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/93e10387-75ba-4f7a-a717-019420f7ac62";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/games" =
    { device = "/dev/disk/by-uuid/93e10387-75ba-4f7a-a717-019420f7ac62";
      fsType = "btrfs";
      options = [ "subvol=@games" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/11fe107a-8ce2-49ff-9b46-0fd97a95334f"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
